# Usa la imagen oficial de PostgreSQL
FROM postgres:latest

# Establece las variables de entorno necesarias
ENV POSTGRES_DB=hotel_search
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Exponer el puerto de PostgreSQL
EXPOSE 5432
